[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  # For proto files
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false
  [[prune.project]]
    name = "github.com/tendermint/tendermint"
    non-go = false
  [[prune.project]]
    name = "github.com/tendermint/tmlibs"
    non-go = false

# overriding here because of IAVL
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.27.0"

[[constraint]]
  name = "golang.org/x/net"
  revision = "292b43bbf7cb8d35ddf40f8d5100ef3837cced3f"

[[override]]
  name = "github.com/gogo/protobuf"
  branch = "master"

# v1.1.0 breaks load_package_test.go
[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "v1.0.0"

[[constraint]]
  name = "golang.org/x/crypto"
  source = "github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

#
#[[override]]
#  name = "github.com/gogo/protobuf"
#  version = "~1.1.0"
#
#[[override]]
#  name = "github.com/golang/protobuf"
#  version = "~1.1.0"
#
[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/jsonschema"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "1.1.0"
