name: develop
on:
  push:
    branches:
    - master
    - release

jobs:
  cover:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go
    - uses: actions/checkout@v2
    - run: make test
      env:
        GO_TEST_ARGS: "-coverprofile=coverage.txt -covermode=atomic"
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker_build
    - name: publish
      env:
        DOCKER_REPO: "hyperledger/burrow"
        DOCKER_REPO_DEV: "quay.io/monax/burrow"
        DOCKER_PASS_DEV: ${{ secrets.DOCKER_PASS_DEV }}
        DOCKER_USER_DEV: ${{ secrets.DOCKER_USER_DEV }}
      run: |
        version=$(./scripts/local_version.sh)
        echo ${DOCKER_PASS_DEV} | docker login --username ${DOCKER_USER_DEV} ${DOCKER_REPO_DEV} --password-stdin
        docker tag ${DOCKER_REPO}:${version} ${DOCKER_REPO_DEV}:${version}
        docker push --all-tags ${DOCKER_REPO_DEV}
