name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  go:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --release-notes "NOTES.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  js:
    name: npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}"
        cd js
        npm install
        npm run build
        npm version $RELEASE_VERSION
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm publish --access public .

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker_build
    - name: publish
      env:
        DOCKER_REPO: "hyperledger/burrow"
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export tag=$(git tag --points-at HEAD)
        echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin
        docker tag ${DOCKER_REPO}:${tag#v} ${DOCKER_REPO}:latest
        docker push ${DOCKER_REPO}
