name: test
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.14]
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - uses: actions/checkout@v1
    - run: make test
    - run: make build
    - uses: actions/upload-artifact@master
      with:
        name: burrow
        path: bin

  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.14]
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - uses: actions/checkout@v1
    - run: make test_integration

  vent:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose run burrow make test_integration_vent

  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - run: make docker_build
      env:
        DOCKER_REPO: "hyperledger/burrow"

  keys:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_keys

  truffle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['8.x']
    needs: unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_truffle

  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_deploy

  restore:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    needs: unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_restore

  js:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['8.x']
    needs: unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make npm_install
        make test_js
