name: test
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v2
    - run: git fetch --unshallow --prune
    - run: make test
    - run: make build
    - uses: actions/upload-artifact@master
      with:
        name: burrow
        path: bin

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - run: make test_integration

  vent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test_integration_vent_postgres

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker_build
      env:
        DOCKER_REPO: "hyperledger/burrow"

  keys:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_keys

  truffle:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_truffle

  deploy:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_deploy

  restore:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make test_restore

  js:
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: actions/download-artifact@master
      with:
        name: burrow
        path: bin
    - run: chmod +x $(pwd)/bin/*
    - name: test
      run: |
        export PATH=${PATH}:$(pwd)/bin
        make yarn_install
        make test_js

  charts:
    runs-on: ubuntu-latest
    env:
      CM_USERNAME: ${{ secrets.CM_USERNAME }}
      CM_PASSWORD: ${{ secrets.CM_PASSWORD }}
      CM_URL:  ${{ secrets.CM_URL }}
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow --prune
    - run: make helm_package
